apiVersion: v1
kind: Service
metadata:
  name: nomad
  namespace: nomad
  labels:
    app: nomad
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.1.13
  selector:
    app: nomad
  ports:
    - name: http
      port: 4646
      targetPort: 4646
      protocol: TCP
    - name: rpc
      port: 4647
      targetPort: 4647
      protocol: TCP
