version: 3

includes:
  tf:
    taskfile: ../../../.task/terraform.yaml

silent: true

env:
  ENVNAME: demo
  STACK: control-plane

tasks:
  default:
    - task: tf:plan

  apply:
    - task: tf:apply
