version: 3

includes:
  tf:
    taskfile: ../../../.task/terraform.yaml

silent: true

env:
  STACK: gcp-client
  ENVNAME: '{{.ENVNAME | default "micro-dt"}}'

tasks:
  default:
    - task: tf:plan

  apply:
    - task: tf:apply
